/**
 * Image Store - SWF Upload
 *
 * @file swupload.js
 * @package Image Store
 * @author Hafid Trujillo
 * @copyright 20010-2013
 * @filesource  wp-content/plugins/image-store/_js/swupload.js
 * @since 3.1.0
 */
 
function imsFileDialogStart(){jQuery("#media-upload-error").empty();swfu.addPostParam("folderpath",jQuery("#_ims_folder_path").val());swfu.addPostParam("cols",jQuery(".sort-images thead th:visible").length)}function imsFileQueued(e){jQuery(".media-blank").remove();if(jQuery("form.type-form #media-items").children().length==1&&jQuery(".hidden","#media-items").length>0){jQuery(".describe-toggle-on").show();jQuery(".describe-toggle-off").hide();jQuery(".slidetoggle").slideUp(200).siblings().removeClass("hidden")}cols=jQuery(".sort-images thead th:visible").length;jQuery("#media-items").prepend('<tr id="media-item-'+e.id+'" class="media-item iedit"><td class="holder" colspan="'+cols+'"><div class="progress"><div class="bar"></div></div><div class="filename original"><span class="percent"></span> '+e.name+"</div></td ></tr>");jQuery(".progress","#media-item-"+e.id).show();jQuery("#cancel-upload").attr("disabled","");jQuery("#insert-gallery").attr("disabled","disabled")}function imsFileError(e,t){var n=jQuery("#media-item-"+e.id);var r=jQuery(".filename",n).text();n.html('<td class="holder" colspan="'+cols+'"><div class="error-div">'+'<a class="dismiss" href="#">'+swfuploadL10n.dismiss+"</a>"+"<strong>"+swfuploadL10n.error_uploading.replace("%s",r)+"</strong><br />"+t+"</div></td>");n.find("a.dismiss").click(function(){jQuery(this).parents(".media-item").slideUp(200,function(){jQuery(this).remove()})})}function imsUploadSuccess(e,t){if(t.match("media-upload-error")){jQuery("#media-item-"+e.id).html(t);return}prepareMediaItem(e,t);updateMediaForm();jQuery(".holder","#media-item-"+e.id).remove();if(jQuery("li.status-publish").length<1)jQuery('<li class="status-publish"><a href="'+imsgal.adminurl+"/post.php?post="+post_id+'&action=edit&status=publish">'+postL10n.published+' <span class="count">(<span>1</span>)</span></a></li>').prependTo(".subsubsub");else jQuery("li.status-publish .count span").html(parseInt(jQuery("li.status-publish .count span").text())+1);if("1"==jQuery("#auto_draft").val()){autosaveLast="";jQuery("#auto_draft").val(2);autosave()}jQuery("#_ims_folder_path, #galleryfolder").val(jQuery("#_ims_folder_path").val()).attr({disabled:"disabled"})}function imsFileQueueError(e,t,n){if(t==SWFUpload.QUEUE_ERROR.QUEUE_LIMIT_EXCEEDED){wpQueueError(swfuploadL10n.queue_limit_exceeded)}else if(t==SWFUpload.QUEUE_ERROR.FILE_EXCEEDS_SIZE_LIMIT){imsFileQueued(e);imsFileError(e,swfuploadL10n.file_exceeds_size_limit)}else if(t==SWFUpload.QUEUE_ERROR.ZERO_BYTE_FILE){imsFileQueued(e);imsFileError(e,swfuploadL10n.zero_byte_file)}else if(t==SWFUpload.QUEUE_ERROR.INVALID_FILETYPE){imsFileQueued(e);imsFileError(e,swfuploadL10n.invalid_filetype)}else{wpQueueError(swfuploadL10n.default_error)}}var uploaderMode=0;var post_id=jQuery("#post_ID").val()