/**
 * Image Store - jQuery XMSlide plugin
 *
 * @file xmslider.jquery.js
 * @package Image Store
 * @author Hafid Trujillo
 * @copyright 20010-2013
 * @filesource  wp-content/plugins/image-store/_js/xmslider.jquery.js
 * @since 3.2.1
 */
 
(function(e){e.fn.xmslide=function(t){var n=e.extend({time:9e3,paging:false,boxsize:false,prevlink:false,nextlink:false,autostart:true,items:".ims-img",innerbox:".ims-gal-innner",onComplete:function(){}},t);this.each(function(){var t;var r=e(this).find(n.items);var i=r.length-1;this.innerbox=e(this).find(n.innerbox);if(this.innerbox.length==0){e(this).wrapInner(e('<div class="innerbox"></div>'));this.innerbox=e(this).find(".innerbox")}this.cropbox=this.innerbox.parent();if(!this.cropbox.hasClass("crop")){this.innerbox.wrap('<div class="crop" ></div>');this.cropbox=e(this).find(".crop")}this.iwidth=iwidth=r.eq(0).outerWidth();if(!n.boxsize)n.boxsize=Math.round(e(this).width()/iwidth);var s=this;this.innerbox.css({width:(iwidth+4)*r.length});this.next=function(){innerbox=this.innerbox;r=e(this).find(n.items);r.eq(0).clone().appendTo(innerbox);e(innerbox).stop().animate({left:-(iwidth*n.boxsize)},function(){r.eq(0).remove();e(innerbox).css({left:-iwidth})})};this.prev=function(){innerbox=this.innerbox;r=e(this).find(n.items);e(innerbox).stop(true,true).animate({left:0},function(){e(innerbox).prepend(r.eq(i).clone());e(innerbox).css({left:-(iwidth*n.boxsize)});r.eq(i).remove()})};if(n.paging){r.each(function(){var t=e(this);t.find("a:has(img)").attr({rel:"image"})});var o="";this.current=1;for(x=1;x<=Math.ceil(r.length/n.boxsize);x++){pageclass=this.current==x?"active pager-link":"pager-link";o+='<a href="#" class="'+pageclass+'">'+x+"</a>"}s.pager=e('<div class="ims-pager">'+o+"</div>").appendTo(this);s.pager.find(".pager-link").click(function(){move=s.iwidth*(e(this).html()-1)*-1*n.boxsize;s.innerbox.stop().animate({opacity:.01},200,function(){s.innerbox.animate({left:move},60).animate({opacity:1},100)});e(this).siblings().removeClass("active");e(this).addClass("active");return false});n.onComplete(this)}if(i>n.boxsize&&!n.paging){s.innerbox.prepend(r.eq(i).clone()).css({left:-iwidth});r.eq(i).remove();if(n.nextlink){e(n.nextlink).click(function(){clearInterval(t);s.next();if(n.autostart)t=setInterval(this.next,n.time);return false})}if(n.prevlink){e(n.prevlink).click(function(){clearInterval(t);s.prev();if(n.autostart)t=setInterval(this.next,n.time);return false})}if(n.autostart)t=setInterval(this.next,n.time);e(this).mouseover(function(){clearInterval(t)});e(this).mouseout(function(){if(n.autostart)t=setInterval(this.next,n.time)})}else{e(n.prevlink).addClass("light").click(function(){return false});e(n.nextlink).addClass("light").click(function(){return false})}})}})(jQuery)