/**
 * Image Store - jQuery XMSlide plugin
 *
 * @file xmslider.jquery.js
 * @package Image Store
 * @author Hafid Trujillo
 * @copyright 20010-2013
 * @filesource  wp-content/plugins/image-store/_js/xmslider.jquery.js
 * @since 3.2.1
 */
 
(function(e){e.fn.xmslide=function(t){var n=e.extend({time:3500,paging:false,boxsize:false,prevlink:false,nextlink:false,autostart:false,items:".ims-img",innerbox:".ims-gal-innner",onComplete:function(){}},t);this.each(function(){var t,r,i;this.linkcount=1;this.interval=false;var s=e(this).find(n.items);var o=s.length-1;this.innerbox=e(this).find(n.innerbox);if(this.innerbox.length==0){e(this).wrapInner(e('<div class="innerbox"></div>'));this.innerbox=e(this).find(".innerbox")}this.cropbox=this.innerbox.parent();if(!this.cropbox.hasClass("crop")){this.innerbox.wrap('<div class="crop" ></div>');this.cropbox=e(this).find(".crop")}this.next=function(){u.linkcount++;u.move_to(u.linkcount)};this.prev=function(){u.linkcount--;u.move_to(u.linkcount)};this.resize=function(){if(!n.boxsize){n.boxsize=Math.ceil(u.cropbox.innerWidth()/s.eq(0).outerWidth())}r=u.cropbox.innerWidth()/n.boxsize;i=Math.ceil(s.length/n.boxsize);u.innerbox.css({width:r*s.length,maxHeight:this.cropbox.outerHeight()});s.each(function(){e(this).css({width:r})})};this.setinterval=function(){u.interval=setInterval(function(){u.linkcount++;if(u.linkcount>i)u.linkcount=1;u.move_to(u.linkcount)},n.time)};this.move_to=function(e){move=r*(e-1)*-1*n.boxsize;u.innerbox.stop(true,true).animate({opacity:.01},400,function(){u.innerbox.animate({left:move},60).animate({opacity:1},300)});if(u.pager){$links=u.pager.find(".pager-link").removeClass("active");$links.eq(e-1).addClass("active")}};var u=this;u.resize();if(n.autostart){this.setinterval();s.bind("mouseleave",function(){u.setinterval()});s.bind("mouseover",function(){clearInterval(u.interval)})}if(n.paging){var a;e(window).bind("resize",function(){clearTimeout(a);a=setTimeout(function(){u.resize()},600)});slidebox=this.innerbox.bind("touchstart",function(e){var t="active";var n=e.originalEvent;var r=n.changedTouches[0].pageX;slidebox.bind("touchmove",function(e){e.preventDefault();var n=u.pager.find(".active");var i=e.originalEvent.touches[0]||e.originalEvent.changedTouches[0];if(i.pageX-r>10){if(u.prev()!=false){n.removeClass(t);n.prev().addClass(t)}}else if(i.pageX-r<0){if(u.next()!=false){n.removeClass(t);n.next().addClass(t)}}slidebox.unbind("touchmove")})});var f="";this.current=1;for(x=1;x<=i;x++){pageclass=this.current==x?"active pager-link":"pager-link";f+='<a href="#" class="'+pageclass+'">'+x+"</a>"}u.pager=e('<div class="ims-pager">'+f+"</div>").appendTo(this);u.pager.find(".pager-link").click(function(t){t.preventDefault();clearInterval(u.interval);u.linkcount=e(this).html();u.move_to(u.linkcount);if(n.autostart)u.setinterval()});n.onComplete(this)}})}})(jQuery)