/**
 * Image Store - imstore tinymce plugin
 *
 * @file imstore.js
 * @package Image Store
 * @author Hafid Trujillo
 * @copyright 20010-2013
 * @filesource  wp-content/plugins/image-store/_js/tinymce/imstore.js
 * @since 3.0.0
 */
 
(function(){tinymce.create("tinymce.plugins.imStore",{init:function(e,n){t=this;t.url=n;e.addCommand("imStoreOpen",function(){e.windowManager.open({inline:1,width:510,height:345,file:n+"/tinymce.php?nonce=347234"},{plugin_url:n})});e.addButton("imstore",{cmd:"imStoreOpen",image:n+"/imstore.png"});e.onBeforeSetContent.add(function(e,n){n.content=t._do_gallery(n.content,t.url,e)});e.onPostProcess.add(function(e,n){if(n.get)n.content=t._get_gallery(n.content)});e.onMouseDown.add(function(e,r){dom=e.dom;target=r.target;el=e.selection.getNode();rectangle=dom.getRect(target);toolbar=dom.create("p",{id:"ims-image-toolbar","data-mce-bogus":"1",contenteditable:false,style:"top:"+rectangle.y+"px; padding:0"});toolbar.appendChild(editgallery=dom.create("i",{"data-mce-bogus":1,"class":"dashicons dashicons-edit im-edit"}));toolbar.appendChild(closelink=dom.create("i",{"data-mce-bogus":1,"class":"dashicons dashicons-no-alt im-remove"}));if(dom.getAttrib(target,"class").indexOf("imsGallery")==0){if(!dom.get("ims-image-toolbar"))e.getBody().appendChild(toolbar);dom.bind(closelink,"click",function(){t._remove(e);dom.remove(el)});dom.bind(editgallery,"click",function(){e.selection.select(el);q=e.dom.getAttrib(el,"title").replace(/\s/g,"&");e.windowManager.open({inline:1,width:510,height:345,file:n+"/tinymce.php?nonce=347234&"+q},{plugin_url:n})})}else if(dom.getAttrib(target,"class").indexOf("dashicons")==-1)t._remove(e)})},_do_gallery:function(e,t,n){return e.replace(/\[ims-gallery([^\]]*)\]/g,function(e,r){return n.dom.createHTML("img",{src:t+"/i.gif",contenteditable:false,"class":"imsGallery mceItem",title:"ims-gallery"+n.dom.encode(r)})})},_getAttr:function(e,t){t=(new RegExp(t+'="([^"]+)"',"g")).exec(e);return t?tinymce.DOM.decode(t[1]):""},_remove:function(e){e.dom.remove(e.dom.get("ims-image-toolbar"))},_get_gallery:function(e){return e.replace(/(?:<p[^>]*>)*(<img[^>]+>)(?:<\/p>)*/g,function(e,n){var r=t._getAttr(n,"class");if(r.indexOf("imsGallery")!=-1)return"<p>["+tinymce.trim(t._getAttr(n,"title"))+"]</p>";return e})}});tinymce.PluginManager.add("imstore",tinymce.plugins.imStore)})();var resize_gal_window=function(e){$object=jQuery("body > .mce-container");if($object.length<1)$object=jQuery("body > .clearlooks2");wt=$object.position().top-e/2;$object.css({height:$object.height()+e+"px",top:wt+"px"});$object.find("iframe").css({height:$object.find("iframe").height()+e+"px"});$object.find(".mce-container-body").css({height:"auto"})}